---
title: 'Configuración y uso de guri'
format: pdf

pdf-engine: lualatex
linkcolor: Sepia
urlcolor: Sepia
editor: visual
lang: es
---

# Instalación de *GURI*

**\[TODO\]** Describir instalación de Gurí.

# Anexo 2: Configuraciones globales de la revista

Además de los archivos tratados anteriormente, cada revista deberá tener otros archivos que permiten configurar la salida.

El archivo `./JUOURNAL/_journal.yaml`: En primer lugar en el directorio raíz de la revista deberá haber un `_journal.yaml` con los datos básicos de la revista.

La carpeta `./JUOURNAL/_config`: A su vez, opcionalmente se podrá generar una carpeta `_config`. En caso de que esta carpeta no se genere se utilizarán las plantillas por defecto. Si existe un archivo `.csl` en esta carpeta se utilizará para generar el citado. En caso contrario se utilizará la configuración por defecto de Pandoc. Si existe un archivo `template.latex` en la carpeta de configuración se utilizará como plantilla. En caso contrario se utilizará un template por defecto (de GURI). Si existe un archivo `latex_metadata.yaml` en la carpeta de configuración se utilizará como plantilla. En caso contrario se utilizará un template por defecto (de GURI).

## Anexo 3: El uso de *GURI*

**\[TODO\]** Describir cómo usar GURI
